### ISSUE TITLE
Idea machine

### ISSUE THREAD

**Issue by viktor-evdokimov** [napolux/1000ideas#1]
Did not read article you linked, but when I was in school we had a subject that could have been remotely translated as "engineering practices" and pretty much half of it was after Theory of Inventive Problem Solving or TRIZ. See this wiki https://en.wikipedia.org/wiki/Genrich_Altshuller.

Just thought you might find it interesting.

**Comment by napolux** [comment]
This is awesome! Thanks for sharing! https://en.wikipedia.org/wiki/TRIZ
