### ISSUE TITLE
Bodyguard as a service

### ISSUE THREAD

**Issue by rstormsf** [napolux/1000ideas#2]
https://github.com/napolux/1000ideas/tree/master/ideas/bodyguard_as_a_service
I really like this idea, I think it can take off

**Comment by napolux** [comment]
It can @rstormsf. The problems are really outlined. Nothing hard to solve, BTW. Just need a bunch of money 💰  for starting it up

**Comment by mniederm** [comment]
Also like this idea, think it would be a good first step to talk to a traditional company which offers such a service now 'offline'.

**Comment by napolux** [comment]
@mniederm the problem is that the service should be like Uber. Can you name a company that can cover an area (i.e. NYC, or smaller cities, like S. Francisco) with a team of bodyguards?
